create database searchrepair2;

CREATE TABLE `searchrepair2`.`method_text_tmp` (
  mid INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  txt VARCHAR(100));
    
 CREATE TABLE `searchrepair2`.`constraints_tmp` (
  gid INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  mid INT NOT NULL,
  pc VARCHAR(1000));
  
  ALTER TABLE searchrepair2.constraints_tmp ADD CONSTRAINT constraints_mid_fk FOREIGN KEY (mid) REFERENCES searchrepair2.method_text_tmp(mid);

    
DELIMITER $$
CREATE PROCEDURE  `searchrepair2`.`ADD_CONSTRAINT`(M INT(11), CON VARCHAR(1000))
BEGIN
	INSERT INTO SEARCHREPAIR2.CONSTRAINTS_TMP(MID, PC) VALUES (M, CON);
END$$
DELIMITER ;

DELIMITER $$
CREATE FUNCTION  `searchrepair2`.`ADD_METHOD_TMP`(TXT VARCHAR(100)) RETURNS int(11)
BEGIN
	INSERT INTO SEARCHREPAIR2.METHOD_TEXT_TMP(TXT) VALUES(TXT);
RETURN LAST_INSERT_ID();
END$$
DELIMITER ;